image: python:3.6-slim

stages:
  - test style
  - validate format
#  - test stories
  - build
#  - deploy

variables:
  BOT_LATEST_IMAGE: $CI_REGISTRY_IMAGE/bot:latest
  WEB_LATEST_IMAGE: $CI_REGISTRY_IMAGE/web:latest

#cache:
#  untracked: true
#  key: "$CI_PROJECT_ID"
#  paths:
#    - .pip/

.cache: &cache
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - venv/
      - .pip

.prepare_tests_dependencies: &tests_dependencies
  before_script:
    - python -m pip install --upgrade pip
    - pip install virtualenv
    - virtualenv venv
    - pip -V
    - python -V # Print out python version for debugging
    - source venv/bin/activate
    - mkdir -p .pip
    - pip --cache-dir=.pip install -r dev.requirements.txt
    - echo $CI_PROJECT_DIR

test style:
  stage: test style
  <<: *cache
  <<: *tests_dependencies
  script:
    - pip -V
    - python -V # Print out python version for debugging
    - flake8 --exclude venv

run dataset validator:
  stage: validate format
  <<: *cache
  script:
    - python -m pip install --upgrade pip
    - source venv/bin/activate
    - pip install -r bot.requirements.txt 
    - cd bot/
    - flake8 --exclude venv
    - make run-validator

#test stories:
#  stage: test stories
#  <<: *cache
#  script:
#    - source venv/bin/activate
#    - cd bot/
#    - make e2e

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY

    - docker build -f docker/bot.Dockerfile -t $BOT_STABLE_IMAGE .
    - docker push $BOT_STABLE_IMAGE

    - docker build -f docker/web.Dockerfile -t $WEB_STABLE_IMAGE .
    - docker push $WEB_STABLE_IMAGE
  environment: homolog
  tags:
    - docker

#deploy_to_homologation:
#  image: cdrx/rancher-gitlab-deploy
#  stage: deploy
#  services:
#    - docker:dind
#  script:
#    - upgrade --environment Production --stack TAIS --service bot --new-image $BOT_STABLE_IMAGE --no-finish-upgrade --debug
#    - upgrade --environment Production --stack TAIS --service actions --new-image $ACTIONS_STABLE_IMAGE --no-finish-upgrade --debug
#    - upgrade --environment Production --stack TAIS --service web --new-image $WEB_STABLE_IMAGE --no-finish-upgrade --debug
#  only:
#    - tags
#  environment: production
#  tags:
#    - docker
#
#
#build latest:
#  image: docker:latest
#  stage: build
#  services:
#    - docker:dind
#  script:
#    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
#
#    - docker build -f docker/bot.Dockerfile -t $BOT_LATEST_IMAGE .
#    - docker push $BOT_LATEST_IMAGE
#
#    - docker build -f docker/actions.Dockerfile -t $ACTIONS_LATEST_IMAGE .
#    - docker push $ACTIONS_LATEST_IMAGE
#
#    - docker build -f docker/web.Dockerfile -t $WEB_LATEST_IMAGE .
#    - docker push $WEB_LATEST_IMAGE
#  only:
#    - /master/
#  environment: development
#  tags:
#    - docker
#
#deploy:
#  image: cdrx/rancher-gitlab-deploy
#  stage: deploy
#  services:
#    - docker:dind
#  script:
#    - upgrade --environment Development --stack TAIS --service bot --new-image $BOT_LATEST_IMAGE --debug
#    - upgrade --environment Development --stack TAIS --service actions --new-image $ACTIONS_LATEST_IMAGE --debug
#    - upgrade --environment Development --stack TAIS --service web --new-image $WEB_LATEST_IMAGE --debug
#  only:
#    - /master/
#  environment: development
#  tags:
#    - docker
