version: '2'

services:
  # ============================= Rocketchat ==================================
  rocketchat:
    image: rocket.chat:0.69.2
    restart: unless-stopped
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - ADMIN_USERNAME=admin
      - ADMIN_PASS=admin
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128



  # ================================= Bot =====================================
  bot:
    image: bot:latest
    build:
      context: .
      dockerfile: ./docker/bot/bot.Dockerfile
    restart: unless-stopped
    env_file:
      - ./docker/bot/bot.env
    ports:
      - 5005:5005
    volumes:
      - ./models:/bot/models/:ro
      - ./bot:/bot
      - ./scripts:/scripts
  
  coach:
    image: coach:latest
    build:
      context: .
      dockerfile: ./docker/bot/coach.Dockerfile
    command: cp -a /src_models/. /models/
    volumes:
      - ./models:/models/
      - ./coach:/coach
      - ./scripts:/scripts

  # =================================== Web ===================================
  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    restart: unless-stopped
    environment:
      - PORT=8000
      - ROCKETCHAT_URL=http://localhost:3000
      - ALLOWED_HOSTS=localhost
      - PREFIX_URL=
    volumes:
      - ./web:/web
    ports:
      - 8000:8000
    depends_on:
      - webdb

  webdb:
    image: postgres:10.5
    restart: unless-stopped
    volumes:
      - ./web/postgres-data:/var/lib/postgresql/data

  # =================================== Kibana-Web ===================================
  kibana-web:
    build:
      context: .
      dockerfile: ./docker/kibana-web.Dockerfile
    restart: unless-stopped
    environment:
      - PORT=8080
      - ALLOWED_HOSTS=localhost
      - PREFIX_URL=
    volumes:
      - ./kibana-web:/kibana-web
    ports:
      - 8080:8080
    depends_on:
      - kibana-webdb

  kibana-webdb:
    image: postgres:10.5
    restart: unless-stopped
    volumes:
      - ./kibana-web/postgres-data:/var/lib/postgresql/data


  # =============================== Analytics =================================
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    restart: unless-stopped
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    restart: unless-stopped
    ports:
      - 5601:5601
    environment:
      - SERVER_PORT=5601
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  replay:
    build:
      context: .
      dockerfile: ./analytics/replay.Dockerfile
    restart: unless-stopped
    environment:
      - ROCKETCHAT_URL=rocketchat:3000
      - ROCKETCHAT_BOT_USERNAME=tais
      - ROCKETCHAT_BOT_PASSWORD=tais
      - BOT_URL=http://bot:5005/webhooks/rest/webhook
    volumes:
      - ./analytics:/analytics
    depends_on:
      - bot

  kibana-tais:
    build:
      context: .
      dockerfile: ./docker/kibana-tais.Dockerfile
    restart: unless-stopped
    environment:
      - PORT=8081
      - ALLOWED_HOSTS=localhost
      - PREFIX_URL=
    volumes:
      - ./kibana-tais:/kibana-tais
    ports:
      - 8081:8081
    depends_on:
      - kibana-taisdb

  kibana-taisdb:
    image: postgres:10.5
    restart: unless-stopped
    volumes:
      - ./kibana-tais/postgres-data:/var/lib/postgresql/data
    ports:
      - 5031:5032



  # =============================== Notebooks =================================
  notebooks:
    build:
      context: .
      dockerfile: ./docker/notebooks.Dockerfile
    volumes:
      - ./bot:/work/bot
      - ./notebooks:/work/notebooks
    ports:
      - 8888:8888

volumes:
  esdata:
    driver: local
